d /etc/media          - - - -
d /etc/models         - - - -
d /etc/labels         - - - -
d /etc/configs        - - - -
d @ROOT_HOME@/media   - - - -
d @ROOT_HOME@/models  - - - -
d @ROOT_HOME@/labels  - - - -
d @ROOT_HOME@/configs - - - -
